### PR TITLE
730 bug legacy wallet cannot decrypt in 278

### LINKED ISSUE #730: [BUG] Legacy wallet cannot decrypt in 2.7.8
### Describe the Bug

Old vault created witthout userid will face login issue when trying to decrypt the vault.

### Expected experience

User should be able to login if correct password in input

### Steps To Reproduce

Remove the id from one of the keyring and login again to see an incorrect password error

### Environment

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #730 

## Summary of Changes

A fallback approach that apply id from deepvault to the vaule when it is missing id.

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [ ] Medium
- [x] High

### CODE REVIEW

File: src/background/service/keyring/index.ts [hunk 1]
```diff
@@ -1274,29 +1274,118 @@ class KeyringService extends EventEmitter {
...
+        console.error(`Failed to process vault entry:`, err, entry);
+        // Continue with next entry
       }
     }
 
     // Store in keyrings array
     this.keyringList = decryptedKeyrings;
   }
 
+  private async checkVaultId(vaultArray: VaultEntry[]) {
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]: Vault entry could be a string?

Comment (zzggo) [reply src/background/service/keyring/index.ts]: if the vault doesn't contain id then it's just the encrypted string.

**Review by tombeckenham — APPROVED** [review]
