### PR TITLE
965 bug security feedbacks

### LINKED ISSUE #965: [BUG] Security Feedbacks
1. All those way to derive the private key are all wrong, I know we are not using it. But don't put wrong or unused code in the project. It's dangerous and misleading.
https://github.com/onflow/FRW-Extension/blob/b7d0ff52db7455414af7af954dd33b44f14d0c74/src/background/service/keyring/hdKeyring.ts#L131

2. Need check chain Id in here, if it's mismatched, we should reject the request:
https://github.com/onflow/FRW-Extension/blob/b7d0ff52db7455414af7af954dd33b44f14d0c74/src/background/controller/provider/controller.ts#L537-L541
https://github.com/onflow/FRW-Extension/blob/b7d0ff52db7455414af7af954dd33b44f14d0c74/src/background/controller/provider/controller.ts#L475-L479

refer to this file:
https://github.com/Outblock/trust-web3-provider/blob/eth-only/src/ethereum_provider.js#L316-L322

3. The way we handle on signMessage decode is way complicated. It should be just hexString to uft8
> const data = Buffer.from(hexString.removePrefix('0x'), 'hex')
> const message = data.toString('utf8')
https://github.com/onflow/FRW-Extension/blob/b7d0ff52db7455414af7af954dd33b44f14d0c74/src/ui/views/Approval/components/EthApproval/EthConfirm/DefaultBlock.tsx#L18-L36

4. We should expand/show sign message by default not collapse it, need change the default behaviour

5. Need maintained a connected dapp list, for the dapp is not connected, we should ignore the requests.
Please refer to this implementation:
https://github.com/RabbyHub/Rabby/blob/e9fecf273294463ad8f2ee97a09259abefdd60fd/src/background/service/permission.ts#L9

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #965 

## Summary of Changes
Removing unused code from the keyring, simplifying data decoding in the signtype display. Optimize the approval page. Check for chain id before making the sign type approval.

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

**Review by tombeckenham — CHANGES_REQUESTED** [review]
The tests fail

File: src/ui/views/Approval/components/EthApproval/EthConfirm/DefaultBlock.tsx [hunk 1]
```diff
@@ -9,18 +9,19 @@ import {
...
-  const hexToString = (hex) => {
-    let str = '';
-    for (let i = 0; i < hex.length; i += 2) {
-      str += String.fromCharCode(parseInt(hex.substr(i, 2), 16));
-    }
-    return str;
+  const [expanded, setExpanded] = useState(true);
+
+  const hexToString = (hexString: string) => {
+    // Remove '0x' prefix if present
```
Comment (tombeckenham) [inline src/ui/views/Approval/components/EthApproval/EthConfirm/DefaultBlock.tsx:27]: This needs to throw an error if the hexString isn't hex. I've tried it and its too easy to pass a non hex encoded string and ask the user to sign it

**Review by tombeckenham — CHANGES_REQUESTED** [review]

**Review by tombeckenham — APPROVED** [review]
