### PR TITLE
846 bug failed in internal transaction

### LINKED ISSUE #846: [BUG] Failed in internal transaction
This bug is reported by Wood which occurs on extension 2.8.0

Internal Move transfers are failing, while external transactions are working as expected.
The sequence number for external transactions is generated by the DApp’s FCL component,
whereas the sequence number for internal transactions is generated by the wallet component.

Currently, we are seeing the following issues:

External EVM execution is failing, but Cadence runs normally.

The error message is shown in :

Image

The internal transaction error is shown in :

Image

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #846 

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: src/background/service/userWallet.ts [hunk 1]
```diff
@@ -177,6 +177,39 @@ class UserWallet {
...
   };
 
+  /**
+   * Gets the keyindex of current account
+   * @returns Number the keyindex of current account
+   */
+  getKeyIndex = async () => {
+    try {
+      const matchingAccount = await this.getCurrentAccount();
+      const keyIndex = matchingAccount.keyIndex;
```
Comment (lmcmz) [inline src/background/service/userWallet.ts]: Better add a handling, if there is no keyindex in matchingAccount. 
We can fallback to fetch it on keyindexer.

File: src/background/service/userWallet.ts [hunk 2]
```diff
@@ -767,20 +800,18 @@ class UserWallet {
 
     // Get the current public key
     const pubKey = this.store.currentPubkey;
+    const matchingAccount = await this.getCurrentAccount();
```
Comment (lmcmz) [inline src/background/service/userWallet.ts]: There is no need to lookup keyindexer everytime to find the account. The account should be cached and load directly from local

File: src/background/service/userWallet.ts [hunk 3]
```diff
@@ -797,10 +828,10 @@ class UserWallet {
```
Comment (lmcmz) [inline src/background/service/userWallet.ts:813]: why we convert the hex string to buffer, and then convert it back to hex string??

```js
const realSignature = await signWithKey(
      Buffer.from(signableMessage, 'hex').toString('hex'),
...
```

**Review by lmcmz — CHANGES_REQUESTED** [review]

File: src/background/service/userWallet.ts (hunk 1 above)
Comment (lmcmz) [reply src/background/service/userWallet.ts]: This `this.getCurrentAccount()` called multiple time when sign a transaction. It's not right.

**Review by lmcmz — APPROVED** [review]
