### PR TITLE
fixed: update the tab commponent with custom style

### LINKED ISSUE #1148: [TASK] Tab Component
### Issue to be solved

There is a new tab component in the [send workflow](https://www.figma.com/design/ELsn1EA0ptswW1f21PZqWp/%F0%9F%9F%A2-Flow-Wallet?node-id=2756-5542&m=dev) that I noticed also in the [settings](https://www.figma.com/design/ELsn1EA0ptswW1f21PZqWp/%F0%9F%9F%A2-Flow-Wallet?node-id=1-12743&t=26rFgQMexgmKlXb9-4). We don't have this component and had to create it from scratch for the settings.

Image

### Suggest A Solution

The new tab component design looks a lot like the tabs in shadcn or base-ui. We should create a component for tabs using either base-ui or shadcn. I'd suggest using base-ui as all we need are the base components and we can add all our own styling - including mui's styling. Use in settings and the send workflow. Use a preset size and have either and expanded (full width) or non expanded (shrinks to text). Don't use MUI tabs as they are heavily styled to look like google

### PR DESCRIPTION
**Pull request by zzggo**
Closes #1148

## Related Issue

Closes #1148

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: src/ui/components/tab.tsx [hunk 1]
```diff
@@ -1,25 +1,32 @@
...
   rightValue = 'two',
+  className,
+  sx,
 }) => {
   return (
     <Box
+      className={className}
       sx={{
         display: 'flex',
         background: '#232323',
```
Comment (tombeckenham) [inline src/ui/components/tab.tsx:32]: Can you use the theme colors for this?

**Review by tombeckenham — APPROVED** [review]
