### PR TITLE
Fixed an issue that caused a null keyring to be added. Fixed an issue that threw an error when trying to access the main wallet before the account was setup. Forced the tests to wait after importing an account for the correct address

### LINKED ISSUE #429: [BUG] Unable to login after importing an account
### Describe the Bug

While running tests, we cannot login after importing a second account

### Expected experience

Being able to login

### Steps To Reproduce

Run the tests on dev branch

### Environment

```markdown
- OS:
- Node:
- npm:
```

### PR DESCRIPTION
**Pull request by tombeckenham**
## Related Issue
Closes #429

## Summary of Changes
Fixed an issue that caused a null keyring to be added. Fixed an issue that threw an error when trying to access the main wallet before the account was setup. Forced the tests to wait after importing an account for the correct address

## Need Regression Testing
Tests prove that login after import works
- [ ] Yes
- [X] No

## Risk Assessment
- [X] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

**Review by zzggo — APPROVED** [review]

File: src/background/controller/wallet.ts [hunk 1]
```diff
@@ -280,6 +280,8 @@ export class WalletController extends BaseController {
     await userWalletService.signOutCurrentUser();
     sessionService.broadcastEvent('accountsChanged', []);
     sessionService.broadcastEvent('lock');
+    // Switch to mainnet
+    await this.switchNetwork('mainnet');
```
Comment (Kay-Zee) [inline src/background/controller/wallet.ts:284]: Whats the reasoning for switching back to mainnet on lock?
