### PR TITLE
882 bug cannot switch to testnet add create account when no account is found

### LINKED ISSUE #883: [FEATURE] Create account on network if none exist
### Issue to be solved

If a user switches to a network (e.g. from mainnet to testnet) and the public key on the first network is not associated with any accounts, the user has no way of creating an account against that key on the network. 

### Suggest A Solution

When we are in the state showing that there are no accounts associated with the public key. i.e. it shows "no accounts found" as the address - then change that instead to a button that says "create address". Change the tooltip to "No accounts found on your public key"

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #883 

## Summary of Changes

add a create manual address option when no address found after retry finish

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: src/background/controller/wallet.ts [hunk 1]
```diff
@@ -287,6 +287,19 @@ export class WalletController extends BaseController {
...
+   * @returns
+   */
+  createManualAddress = async () => {
+    const accountKey = userWalletService.getCurrentAccountKey();
+    setCachedData(registerStatusKey(accountKey.public_key), true);
+
+    const data = await openapiService.createManualAddress(accountKey);
+    const txid = data.data.txid;
+    this.checkForNewAddress(txid);
+  };
```
[the remark this answers is not in the document]
Comment (tombeckenham) [reply src/background/controller/wallet.ts]: How do you suggest fixing it?

File: src/background/service/userWallet.ts [hunk 2]
```diff
@@ -140,6 +146,13 @@ class UserWallet {
     return this.store.currentPubkey;
   };
 
+  getCurrentAccountKey = (): AccountKeyRequest => {
```
Comment (tombeckenham) [inline src/background/service/userWallet.ts]: You definately should not need this

File: src/background/service/userWallet.ts [hunk 3]
```diff
@@ -90,6 +90,12 @@ const USER_WALLET_TEMPLATE: UserWalletStore = {
   network: 'mainnet',
   emulatorMode: false,
   currentPubkey: '',
+  account_key: {
```
Comment (tombeckenham) [inline src/background/service/userWallet.ts]: We should definately not need to have a duplication of public key.

File: src/background/controller/wallet.ts [hunk 4]
```diff
@@ -287,6 +287,19 @@ export class WalletController extends BaseController {
     }
   };
 
+  /**
+   * Create a manual address
+   * @returns
+   */
+  createManualAddress = async () => {
+    const accountKey = userWalletService.getCurrentAccountKey();
```
Comment (tombeckenham) [inline src/background/controller/wallet.ts]: Get the current Public key tuple from key ring - then compare the public key to figure out which algo was used. Create a utility function in account-key.ts that takes a public key string, and a tuple and returns an `AccountKeyRequest`. You'll find the default algos somewhere

**Review by tombeckenham — COMMENTED** [review]
Please don't store account key in the userWallet. I've added comments for how you should change that

**Review by tombeckenham — APPROVED** [review]
