### PR TITLE
fixed: replace the image when rendering url with a placeholder

### LINKED ISSUE #506: [FEATURE] Display the dapp image with the correct icon
### Issue to be solved

Show an image with correct format or a placeholder when linking with dapp

### Suggest A Solution

_No response_

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #506

## Need Regression Testing

- [ ] Yes
- [x] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

**Review by caosbad — APPROVED** [review]

File: src/ui/views/Approval/components/EthApproval/EthApprovalComponents/IconWithPlaceholder.tsx [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+        width,
+        height,
+        borderRadius,
+        backgroundColor,
+      }}
+      image={imageUrl}
+      onError={(e) => {
+        e.currentTarget.onerror = null;
+        e.currentTarget.src = flowgrey;
+      }}
```
Comment (tombeckenham) [inline src/ui/views/Approval/components/EthApproval/EthApprovalComponents/IconWithPlaceholder.tsx:34]: Try using the Google favicon api as a fallback. It should work nicely

```suggestion
        e.currentTarget.src = `https://www.google.com/s2/favicons?sz=256&domain_url=${imageUrl}`;
```

**Review by tombeckenham — APPROVED** [review]
