### PR TITLE
fixed: new list tab rendering method, fix the multiple rendering issue

### LINKED ISSUE #589: [FEATURE] imporve the rendering in cadence NFT components
### Issue to be solved

The component loads multiple times when loading it the first time. Investigate the cause and fix the multiple renderings.

### Suggest A Solution

_No response_

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #589 

## Summary of Changes

Here's a fix for multiple rendering in the NFT component

## Need Regression Testing

check the page of the NFT component to see if there's any display issue

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: src/ui/views/NFT/ListTab.tsx [hunk 1]
```diff
@@ -74,71 +83,96 @@ const ListTab = forwardRef((props: ListTabProps, ref) => {
...
+      });
     }
-  }, [props.data.ownerAddress, fetchCollectionCache]);
+
+    return () => {
+      mounted = false;
+    };
+  }, [currentWallet, state.ownerAddress, fetchCollectionCache]);
+
+  useImperativeHandle(
```
Comment (tombeckenham) [inline src/ui/views/NFT/ListTab.tsx:159]: What's this ref used for?

File: src/ui/views/NFT/ListTab.tsx [hunk 2]
```diff
@@ -357,13 +391,13 @@ const ListTab = forwardRef((props: ListTabProps, ref) => {
...
       ) : (
-        collections.map(createListCard)
+        state.collections.map(createListCard)
       )}
     </Container>
   );
 });
 
-export default ListTab;
+export default React.memo(ListTab);
```
Comment (tombeckenham) [inline src/ui/views/NFT/ListTab.tsx:403]: Why use React.memo here?

**Review by tombeckenham — APPROVED** [review]
