### PR TITLE
fixed: hide verified as default make tokenlist use the hook

### LINKED ISSUE #950: Add token issue in

### PR DESCRIPTION
**Pull request by zzggo**
Closes #950

## Related Issue

Closes #950 

## Summary of Changes

Make the tokenlist hide unverified token as default, fixed an undefined .tofixed issue on tokendetail page.

image

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: src/ui/FRWComponent/StorageUsageCard.tsx [hunk 1]
```diff
@@ -59,7 +59,11 @@ export const StorageUsageCard: React.FC = () => {
             {usagePercentage.toFixed(2)}%
           </Typography>
           <Typography variant="body2" color="text.secondary">
-            {`${used.toFixed(1)} ${usedUnit} / ${capacity.toFixed(1)} ${capacityUnit}`}
+            {(() => {
```
Comment (tombeckenham) [inline src/ui/FRWComponent/StorageUsageCard.tsx:62]: Note there's an open ticket to consolidate the storage usage card. It's duplcated in the code in a weird way. You might want to find the other one and fix that too (or consolidate)

File: src/background/controller/wallet.ts [hunk 2]
```diff
@@ -828,6 +828,11 @@ export class WalletController extends BaseController {
     return privateKey;
   };
 
+  getPubKeyPrivateKey = async (password: string): Promise<PublicPrivateKeyTuple> => {
```
Comment (tombeckenham) [inline src/background/controller/wallet.ts:745]: We already have a method - retrievePk. Either remove that method or this one. Also if getPrivateKeyForCurrentAccount is not used, please remove it. Any method that returns the private key is a potential security hole.

File: src/ui/views/Setting/privatekey/Keydetail.tsx [hunk 3]
```diff
@@ -14,42 +17,54 @@ interface State {
 
 const Keydetail = () => {
   const location = useLocation<State>();
-  const usewallet = useWallet();
+  const wallet = useWallet();
+  const { userWallets } = useProfiles();
```
Comment (tombeckenham) [inline src/ui/views/Setting/privatekey/Keydetail.tsx]: get the current algo etc from the main account. It'll be on parentWallet

File: src/ui/FRWComponent/StorageUsageCard.tsx (hunk 1 above)
Comment (zzggo) [reply src/ui/FRWComponent/StorageUsageCard.tsx:62]: Sure, this one is only a fix for avoiding the page from turning blank when the used value is not a number.

File: src/ui/hooks/useProfileHook.ts [hunk 4]
```diff
@@ -159,5 +158,6 @@ export const useProfiles = () => {
     canMoveToChild,
     currentWalletList,
     payer,
+    userWallets,
```
Comment (tombeckenham) [inline src/ui/hooks/useProfileHook.ts]: I'm thinking you should use the parentWallet to get what you need. It will have the publicKey, signAlgo etc in that

**Review by tombeckenham — CHANGES_REQUESTED** [review]
Please get the public key, sign algo etc from the parentWallet in useProfiles. Also check which private key methods you should keep in wallet and get rid of the rest

File: src/ui/hooks/useProfileHook.ts [hunk 5]
```diff
@@ -28,31 +29,29 @@ import {
...
+const INITIAL_WALLET: WalletAccount = {
   name: '',
   icon: '',
   address: '',
-  chain_id: 'flow',
   id: 1,
-  coins: ['flow'],
   color: '',
   chain: MAINNET_CHAIN_ID,
 };
```
[the remark this answers is not in the document]
Comment (zzggo) [reply src/ui/hooks/useProfileHook.ts:39]: It's not used, its keys in the old type

File: src/ui/views/Setting/privatekey/Keydetail.tsx [hunk 6]
```diff
@@ -14,42 +17,54 @@ interface State {
 
 const Keydetail = () => {
   const location = useLocation<State>();
-  const usewallet = useWallet();
+  const wallet = useWallet();
+  const { parentWallet } = useProfiles();
   const [privatekey, setKey] = useState('');
-  const [publickey, setPublicKey] = useState('');
   const [hashAlgorithm, setHash] = useState('');
   const [signAlgorithm, setSign] = useState('');
```
Comment (tombeckenham) [inline src/ui/views/Setting/privatekey/Keydetail.tsx]:
```suggestion
    const hashAlgorithm = parentWallet?.hashAlgoString;
    const signAlgorithm = parentWallet?.signAlgoString;


```

**Review by tombeckenham — CHANGES_REQUESTED** [review]
You don't need all this stuff in KeyDetail to get the algos etc. Just get the values straight from parentWallet

File: src/ui/views/Setting/privatekey/Keydetail.tsx [hunk 7]
```diff
@@ -14,42 +17,45 @@ interface State {
...
   const verify = useCallback(async () => {
     try {
       const pwd = location.state.password;
-      const result = await usewallet.getPrivateKeyForCurrentAccount(pwd);
-      setKey(result);
 
-      const pubKey = await storage.get('pubKey');
-      const account = await getLoggedInAccount();
-      const { hashAlgoString: hashAlgo, signAlgoString: signAlgo } = account;
+      if (!parentWallet?.publicKey) {
```
Comment (tombeckenham) [inline src/ui/views/Setting/privatekey/Keydetail.tsx]: You should just wait until this is defined. It should be in loading state before then

File: src/ui/views/Setting/privatekey/Keydetail.tsx [hunk 8]
```diff
@@ -14,42 +17,45 @@ interface State {
...
+      }
     }
-  }, [usewallet]);
+  }, [location.state.password, wallet, parentWallet]);
 
   useEffect(() => {
-    setTab();
     verify();
-  }, [verify, setTab]);
+  }, [verify]);
```
Comment (tombeckenham) [inline src/ui/views/Setting/privatekey/Keydetail.tsx]:
```suggestion
  useEffect(() => {
    if (parentWallet?.publicKey) {
      verify();
    }
  }, [parentWallet?.publicKey, verify]);
```

File: src/ui/views/Setting/privatekey/Keydetail.tsx [hunk 9]
```diff
@@ -14,42 +17,45 @@ interface State {
...
+  const wallet = useWallet();
+  const { parentWallet } = useProfiles();
   const [privatekey, setKey] = useState('');
-  const [publickey, setPublicKey] = useState('');
-  const [hashAlgorithm, setHash] = useState('');
-  const [signAlgorithm, setSign] = useState('');
 
   const verify = useCallback(async () => {
     try {
       const pwd = location.state.password;
```
Comment (tombeckenham) [inline src/ui/views/Setting/privatekey/Keydetail.tsx:27]: You should handle the case where this is undefined. E.g. if the user reloads the page

Comment (zzggo) [reply src/ui/views/Setting/privatekey/Keydetail.tsx:27]: it will redirect to the enter password page if reload since the password state is gone

**Review by tombeckenham — APPROVED** [review]

**Review by tombeckenham — APPROVED** [review]
