### PR TITLE
685 bug profile switching issues

### LINKED ISSUE #685: [BUG] Profile Switching Issues
### Describe the Bug

Now that we've removed the need to unlock the wallet with switching profiles, the user can perform operations and click around while switching. This can get the wallet into a state where it half uses data from the old profile. The mobile products prevent the user from doing anything while switching.

Problems I see right now are:
1. The user can close the popup and switching menu while switching and navigate to try to send tokens
2. The user can try to switch to another profiile while they are switching - causing two switch operations to happen at once
3. The e2e tests fail as they expect a login screen when switching profiles

### Expected experience

1. When switching profiles, the profile selector (Popup) should be closed leaving the account menu open. The user should be prevented from opening the profile selector until the switch is complete. They might be able to open and close the window, but they should not be able to do anything until the switch is complete. I'm not 100% sure how we implement this, but something like that has to happen until we change the data caching strategy to not overwrite data.
2. The e2e tests should be updated so that it accounts for this new user flow. Specifically look at `loginToExtensionAccount` in the helper.ts file

### Steps To Reproduce

1. Open the profile switcher
2. Click another profile

### Environment

```markdown
dev branch for release after 2.7.7
```

### PR DESCRIPTION
**Pull request by zzggo**
## Related Issue

Closes #685 

## Summary of Changes

image

Added a loading cover and hide the sidebar when switching account to prevent user from clicking other thing. removed the password input in the e2e testing

## Need Regression Testing

- [ ] Yes
- [x] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

### CODE REVIEW

File: e2e/utils/helper.ts [hunk 1]
```diff
@@ -107,9 +107,9 @@ export const loginToExtensionAccount = async ({ page, extensionId, addr, passwor
     // Switch to the correct account. Note doest not handle more than 3 accounts loaded
     await page.getByRole('button', { name: 'avatar' }).getByText(addr).click();
 
-    await page.getByPlaceholder('Enter your password').clear();
-    await page.getByPlaceholder('Enter your password').fill(password);
-    await page.getByRole('button', { name: 'Unlock Wallet' }).click();
+    // await page.getByPlaceholder('Enter your password').clear();
+    // await page.getByPlaceholder('Enter your password').fill(password);
+    // await page.getByRole('button', { name: 'Unlock Wallet' }).click();
```
Comment (lmcmz) [inline e2e/utils/helper.ts]: If those checks are no used anymore, shouldn't we just remove those ?

**Review by lmcmz — APPROVED** [review]

**Review by tombeckenham — APPROVED** [review]
Nice work
