### PR TITLE
fixed: use the selected address

### LINKED ISSUE #1027: [BUG] Account Keys doesn't support multi-account
### Describe the Bug

The account key list in the extension shows the keys for the active account instead of the account that is selected in the list. This is very misleading.

### Expected experience

The account keys list should show the keys of the account that you select in the account list. it should take the address as a url param

### Steps To Reproduce

1. Create a profile with 2 accounts
2. Add a key to one of the accounts with flow port
3. Make the other account active (active the account that has only one key)
4. Go to Settings > Accounts > Account Keys for the account which should have two keys

You'll only see the keys from the active account, not the one you selected

### Environment

```markdown
2.8.5
```

### PR DESCRIPTION
**Pull request by zzggo**
Closes #1027

## Related Issue

Closes #1027

## Summary of Changes

Pass the selected address to the key list and fetch the key list for that address.

## Need Regression Testing

- [x] Yes
- [ ] No

## Risk Assessment

- [x] Low
- [ ] Medium
- [ ] High

### CODE REVIEW

File: src/background/controller/wallet.ts [hunk 1]
```diff
@@ -3354,6 +3354,16 @@ export class WalletController extends BaseController {
...
 
+  getCurrentAddressInfo = async (address: string): Promise<FclAccount> => {
+    if (!address) {
+      throw new Error('No address found');
+    }
+    if (!isValidFlowAddress(address)) {
+      throw new Error('Invalid address');
+    }
+    return await fcl.account(address);
+  };
```
Comment (tombeckenham) [inline src/background/controller/wallet.ts]: Use getAccountInfo instead

```suggestion
```

File: src/ui/views/Setting/KeyList/KeyList.tsx [hunk 2]
```diff
@@ -17,14 +18,17 @@ import RevokePage from './RevokePage';
...
   const [showRevoke, setShowRevoke] = useState(false);
   const [publickeys, setPublicKeys] = useState<any[]>([]);
   const [keyIndex, setKeyIndex] = useState<string>('');
 
   const getAccount = useCallback(async () => {
-    const account = await wallet.getMainAccountInfo();
     const keys = await wallet.openapi.keyList();
+
+    const account = await wallet.getCurrentAddressInfo(address);
     const installationId = await wallet.openapi.getInstallationId();
```
Comment (tombeckenham) [inline src/ui/views/Setting/KeyList/KeyList.tsx]:
```suggestion
    const account = await wallet.getAccountInfo(address);
    const installationId = await wallet.openapi.getInstallationId();
```

**Review by tombeckenham — APPROVED** [review]
