### PR TITLE
666 feature delete profile feature

### LINKED ISSUE #666: [FEATURE] "Delete Profile" Feature
### Issue to be solved

Currently there is a reset wallet feature that - rightly or wrongly - resets all data on the user's device removing every single profile. This is a dangerous feature as it requires the user has backed up every one of their wallets.

A more likely scenario is that the user wants to remove one profile from their wallet. 

### Suggest A Solution

- [x] Implement a remove profile feature that removes the keys associated with that one profile. If the user has just one profile, it would do the same as reset wallet. 
- [x] Put this button on the profile setting page.
- [x] Move the reset wallet button from the account setting screen to the profile screen as well

I'd also be happy with having a single button that gave the option of reseting everything on the confirmation dialog.

### PR DESCRIPTION
**Pull request by bthaile**
## Related Issue

Closes #666 

## Summary of Changes

Created remove profile modal
Updated translations messages.json

## Need Regression Testing

Need to test removing profile and user wallet is logged out
When last profile is removed user is directed to welcome in new tab.

- [x] Yes
- [ ] No

## Risk Assessment

- [ ] Low
- [x] Medium
- [ ] High

## Additional Notes

Moved reset wallet button from account setting page to Profile settings page

## Screenshots (if applicable)

remove profile 
image

existing reset wallet
image

### CODE REVIEW

File: src/background/service/keyring/index.ts [hunk 1]
```diff
@@ -1652,6 +1652,92 @@ class KeyringService extends EventEmitter {
...
+    }
+
+    // Get the current profile ID
+    const currentId = await returnCurrentProfileId();
+
+    // If we're removing the current profile, first switch to another one
+    let needToSwitchKeyring = false;
+    if (currentId === profileId) {
+      // Find another profile to switch to
+      const nextProfileId = keyringIds.find((id) => id !== profileId);
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]:
```suggestion
      const nextProfileId = keyringIds[Math.min(profileIndex,keyringIds.length - 1)]
```

File: src/ui/views/Setting/Account/index.tsx [hunk 2]
```diff
@@ -144,10 +156,69 @@ const AccountSettings = () => {
...
+    setRemoveError('');
+
+    try {
+      // Get the current profile ID
+      const userInfo = await wallet.getUserInfo(false);
+      const profileId = userInfo.id;
+
+      if (!profileId) {
+        throw new Error('Could not determine profile ID');
+      }
```
Comment (tombeckenham) [inline src/ui/views/Setting/Account/index.tsx]: Use getCurrentProfileId() - note you need to import it too

```suggestion
    const profileId = await getCurrentProfileId();

```

File: src/background/service/keyring/index.ts [hunk 3]
```diff
@@ -1652,6 +1652,92 @@ class KeyringService extends EventEmitter {
...
+    const keyringIds = await this.getKeyringIds();
+
+    // If this is the only profile, reset the entire wallet
+    if (keyringIds.length <= 1) {
+      await this.resetKeyRing();
+      // Update the memory store
+      this.memStore.updateState({ isUnlocked: false });
+      this.emit('lock');
+      return true;
+    }
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]: This isn't going to work, unfortunately. This will leave the user with an empty vault but a password set. If the user tries to unlock the wallet, they'll get stuck.

Comment (tombeckenham) [reply src/background/service/keyring/index.ts]: I think you'll also need to clear the current profile id

File: src/background/service/keyring/index.ts [hunk 4]
```diff
@@ -1652,6 +1652,92 @@ class KeyringService extends EventEmitter {
...
+
+    // Find the profile in the keyring list
+    const profileIndex = this.keyringList.findIndex((keyring) => keyring.id === profileId);
+    if (profileIndex === -1) {
+      throw new Error(`Profile with ID ${profileId} not found`);
+    }
+
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]: I'd make check that profileId exists before checking if there's only one keyring

File: src/background/service/keyring/index.ts [hunk 5]
```diff
@@ -1652,6 +1652,92 @@ class KeyringService extends EventEmitter {
...
+    // Clear all accounts from the keyring (if it's currently active)
+    if (this.currentKeyring.length > 0 && currentId === profileId) {
+      for (const keyring of this.currentKeyring) {
+        if (typeof keyring.removeAllAccounts === 'function') {
+          await keyring.removeAllAccounts();
+        }
+      }
+    }
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]: I'm not actually sure what this does. This is some remnant of the EOA model from Metamask

File: src/background/service/keyring/index.ts [hunk 6]
```diff
@@ -1652,6 +1652,92 @@ class KeyringService extends EventEmitter {
...
+    // Switch to another profile if needed
+    if (needToSwitchKeyring) {
+      const nextProfileId = keyringIds.find((id) => id !== profileId);
+      if (nextProfileId) {
+        this.currentKeyring = await this.switchKeyring(nextProfileId);
+      }
+    }
+
+    // Persist the changes to storage
+    await this.persistAllKeyrings(password);
```
Comment (tombeckenham) [inline src/background/service/keyring/index.ts]: Calling persistAllKeyrings assumes we have a current keyring first. I'd use `await this.encryptVaultArray(updatedVault, password);` . After doing that, I'd call `switchKeyring`

File: src/ui/FRWComponent/PopupModal/remove-profile-modal.tsx [hunk 7]
```diff
@@ -0,0 +1,192 @@
...
+          mb: 3,
+          input: { color: '#FFFFFF' },
+          '& .MuiOutlinedInput-root': {
+            '& fieldset': { borderColor: '#787878' },
+          },
+          '& .MuiFormLabel-root': {
+            color: '#BABABA',
+          },
+        }}
+      />
```
Comment (tombeckenham) [inline src/ui/FRWComponent/PopupModal/remove-profile-modal.tsx:137]: Is there anyway to create a single password component and reuse it? e.g. the one from the unlock screen?

**Review by tombeckenham — CHANGES_REQUESTED** [review]
It's a good start, but quite a few changes needed. I'm mentioned some in the issue as well. I'm also thinking we should add an e2e test. We could add to the registration / login tests. Register an account, import a second profile (e.g. the sender ci one. We can do that as we're on a second instance of the wallet in that registration project). Remove the sender ci account. Then in a second test, remove the account we just created.

File: src/background/service/keyring/index.ts (hunk 4 above)
Comment (bthaile) [reply src/background/service/keyring/index.ts]: I'll make a code change, moving the check that profileId exists first thing, before doing any processing.

File: src/background/service/keyring/index.ts (hunk 5 above)
Comment (bthaile) [reply src/background/service/keyring/index.ts]: its confusing, it makes sure that each keyring is cleaned up by removeAllAccounts. It is a bit of an overkill.

File: src/background/service/keyring/index.ts (hunk 3 above)
Comment (bthaile) [reply src/background/service/keyring/index.ts]: I didn't run into an issue where the user got to the unlock screen cuz there was no profiles to load they were redirected to the "fresh" wallet screen. I'll make changes to make sure there are no edge cases.

File: src/ui/FRWComponent/PopupModal/remove-profile-modal.tsx (hunk 7 above)
Comment (bthaile) [reply src/ui/FRWComponent/PopupModal/remove-profile-modal.tsx:137]: https://github.com/onflow/FRW-Extension/issues/861

Created a ticket to consolidate user password input. Since I have another PR in review that would need to be updated along with existing code. Might as well do all this effort in one ticket.

**Review by tombeckenham — COMMENTED** [review]
Can you add an e2e test? Let me know if you need help with that

**Review by tombeckenham — APPROVED** [review]
Good work. I added an e2e test. Please resolve conflicts then merge after e2e tests complete
